#! /bin/sh

echo "* repack" && git repack -adf && \
    echo "* prune" && git prune && \
    echo "* prune-packed" && git prune-packed && \
    echo "* gc" && git gc --aggressive && \
    echo "* done"
