#! /bin/sh

cmd=${0##*/}

if [ "$cmd" == "wip" ]
then
    git add . && git commit -m WIP && git push --force
elif [ "$cmd" == "unwip" ]
then
    while [ "$(git log --format="%s" HEAD~1..)" == "WIP" ]
    do
        git reset --hard HEAD~1
    done
    git pull || exit 1
    while [ "$(git log --format="%s" HEAD~1..)" == "WIP" ]
    do
        git reset --soft HEAD~1
    done
    git reset && git status
else
    echo "unknown cmd '$cmd'" && exit 1
fi
